### ISSUE TITLE
error while rexecuting python3 tbw.py

### ISSUE THREAD

**Issue by amolmt** [galperins4/tbw#28]
I am getting the following error while executing tbw.py from core_v1 dir
and I am using this script for LWF node
here's the error:

python3 tbw.py 
Traceback (most recent call last):
  File "tbw.py", line 435, in <module>
    username = get_dbname()
  File "tbw.py", line 417, in get_dbname
    uname = network[data['network']]['db_user']
KeyError: 'network'

**Comment by galperins4** [comment]
Usually this is caused by having the network incorrect in the config.json file. What is the parameter you have specified in config.json for network?

**Comment by galperins4** [comment]
Closed as lwf is no longer supported
